import type { Metadata } from "next";
import { getSession } from "@auth0/nextjs-auth0";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { type ButtonVariants, button } from "@/components/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        {!session && (
          <div className="h-svh w-svw grid place-content-center">
            <Link
              href={"/api/auth/login"}
              className={button({ intent: "primary" })}
            >
              Please log in
            </Link>
          </div>
        )}
        {session && <UserProvider>{children}</UserProvider>}
      </body>
    </html>
  );
}
